# Generated by Django 6.0.3 on 2026-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventposition',
            options={'ordering': ['position__airport_icao', 'position__callsign'], 'verbose_name': 'Event Position', 'verbose_name_plural': 'Event Positions'},
        ),
        migrations.AddField(
            model_name='event',
            name='roster_published',
            field=models.BooleanField(default=False, help_text='When true, the roster is visible to controllers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Fallback external banner URL'),
        ),
        migrations.AlterField(
            model_name='eventposition',
            name='min_rating',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum VATSIM rating'),
        ),
    ]
