# Generated by Django 6.0.4 on 2026-04-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventposition_options_event_roster_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventposition',
            options={'ordering': ['position__airport_icao', 'position__callsign', 'start_time'], 'verbose_name': 'Event Position', 'verbose_name_plural': 'Event Positions'},
        ),
        migrations.AddField(
            model_name='eventavailability',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='When the controller is available from', null=True),
        ),
        migrations.AddField(
            model_name='eventavailability',
            name='available_to',
            field=models.DateTimeField(blank=True, help_text='When the controller is available until', null=True),
        ),
        migrations.AddField(
            model_name='eventposition',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Slot end — defaults to event end if blank', null=True),
        ),
        migrations.AddField(
            model_name='eventposition',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Slot start — defaults to event start if blank', null=True),
        ),
    ]
