# Generated by Django 6.0.4 on 2026-04-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='roster_public',
            field=models.BooleanField(default=False, help_text='When true, the roster is also visible on the public event page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='roster_published',
            field=models.BooleanField(default=False, help_text='When true, the roster is visible to logged-in controllers'),
        ),
    ]
