# Generated by Django 6.0.4 on 2026-04-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_roster_public_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventposition',
            name='min_rating',
        ),
    ]
