# Generated by Django 6.0.4 on 2026-04-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventposition_min_rating'),
        ('public', '0006_runway_split_preferential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventposition',
            options={'ordering': ['position__airport__icao', 'position__callsign', 'start_time'], 'verbose_name': 'Event Position', 'verbose_name_plural': 'Event Positions'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='airport_icao',
        ),
        migrations.AddField(
            model_name='event',
            name='airport',
            field=models.ForeignKey(blank=True, help_text='Primary airport for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.airport'),
        ),
    ]
