# Generated by Django 6.0.3 on 2026-03-30 16:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VATéir Control Centre', help_text='Displayed in the browser title bar and login page', max_length=100)),
                ('topbar_text', models.CharField(default='VATéir', help_text='Text displayed in the top navigation bar', max_length=100)),
                ('fir_name', models.CharField(default='Shannon/Dublin FIR', help_text="FIR name for display (e.g. 'Shannon/Dublin FIR')", max_length=100)),
                ('fir_long_name', models.CharField(default='Shannon and Dublin FIR (Ireland)', help_text='Full FIR name with location', max_length=200)),
                ('callsign_prefixes', models.CharField(default='EI', help_text="Comma-separated callsign prefixes to track (e.g. 'EI')", max_length=200)),
                ('metar_icaos', models.CharField(default='EIDW,EINN,EICK', help_text="Comma-separated ICAO codes for METAR display (e.g. 'EIDW,EINN,EICK')", max_length=200)),
                ('enable_metar_widget', models.BooleanField(default=True)),
                ('enable_events_page', models.BooleanField(default=True)),
                ('enable_feedback_page', models.BooleanField(default=True)),
                ('primary_color_from', models.CharField(default='#059669', help_text='Gradient start colour (hex)', max_length=7)),
                ('primary_color_to', models.CharField(default='#10b981', help_text='Gradient end colour (hex)', max_length=7)),
                ('hero_title', models.CharField(default='Welcome to VATéir', help_text='Main hero heading on the homepage', max_length=200)),
                ('hero_subtitle', models.TextField(default='Virtual Air Traffic Control for Ireland — Shannon and Dublin FIR', help_text='Subtitle text below the hero heading')),
                ('discord_webhook_url', models.URLField(blank=True, help_text='Discord webhook for notifications')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cid', models.PositiveIntegerField(blank=True, help_text='VATSIM Certificate ID', null=True, unique=True)),
                ('vatsim_name', models.CharField(blank=True, help_text='Full name as returned by VATSIM OAuth2', max_length=255)),
                ('name_display', models.CharField(choices=[('HIDDEN', 'Hidden (show CID only)'), ('FIRST_NAME', 'First name only'), ('INITIALS', 'Initials only'), ('FULL_NAME', 'Full name')], default='FULL_NAME', help_text="How this user's name appears to authenticated visitors", max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField(default=1, help_text='VATSIM rating integer (1=OBS ... 12=ADM)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('MENTOR', 'Mentor'), ('EXAMINER', 'Examiner')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
