# Generated by Django 6.0.3 on 2026-04-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='discord_events_channel_id',
            field=models.CharField(blank=True, help_text='Channel for event notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='discord_general_channel_id',
            field=models.CharField(blank=True, help_text='Channel for general notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='discord_guild_id',
            field=models.CharField(blank=True, help_text='Discord server/guild ID', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='discord_roster_channel_id',
            field=models.CharField(blank=True, help_text='Channel for roster sync notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='discord_training_channel_id',
            field=models.CharField(blank=True, help_text='Channel for training notifications', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='discord_webhook_url',
            field=models.URLField(blank=True, help_text='Legacy webhook URL (use bot channels below instead)'),
        ),
    ]
