# Generated by Django 6.0.3 on 2026-04-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siteconfig_discord_events_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_user_id',
            field=models.CharField(blank=True, default='', help_text='Discord user snowflake ID', max_length=20),
        ),
    ]
