# Generated by Django 6.0.3 on 2026-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_discord_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='discord_tickets_channel_id',
            field=models.CharField(blank=True, help_text='Channel for support ticket notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enable_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ticket_sla_hours',
            field=models.PositiveIntegerField(default=48, help_text='Hours before a ticket is considered SLA-breached'),
        ),
    ]
