# Generated by Django 6.0.3 on 2026-04-06 15:35

from django.db import migrations


DEFAULT_PERMISSIONS = [
    ("admin_panel.access", "Access Admin Panel", "Admin"),
    ("admin_panel.site_config", "Manage Site Configuration", "Admin"),
    ("roles.manage", "Grant/Revoke Roles and Permissions", "Admin"),
    ("controllers.manage", "Manage Controller Profiles", "Controllers"),
    ("controllers.view_notes", "View Staff Notes on Controllers", "Controllers"),
    ("documents.manage", "Upload/Edit/Delete Documents", "Documents"),
    ("events.manage", "Create/Edit/Delete Events", "Events"),
    ("events.manage_roster", "Assign Controllers to Event Positions", "Events"),
    ("feedback.manage", "Review and Action Feedback", "Feedback"),
    ("tickets.manage", "Manage Support Tickets", "Tickets"),
    ("training.mentor", "Conduct Training Sessions", "Training"),
    ("training.examine", "Conduct Examinations (OTS/CPT)", "Training"),
    ("training.manage", "Manage Training Requests and Courses", "Training"),
    ("staff_page.manage", "Manage Public Staff Page", "Staff"),
    ("visitors.manage", "Approve/Reject Visiting Controllers", "Controllers"),
]

STAFF_PERMS = [
    "admin_panel.access", "controllers.manage", "controllers.view_notes",
    "documents.manage", "events.manage", "events.manage_roster",
    "feedback.manage", "tickets.manage", "visitors.manage",
]

ROLE_PROFILES = [
    ("Superadmin", "Full system access", True, [p[0] for p in DEFAULT_PERMISSIONS]),
    ("Admin", "Administrative access", True, STAFF_PERMS + [
        "admin_panel.site_config", "roles.manage", "staff_page.manage",
        "training.manage",
    ]),
    ("Staff", "General staff access", True, STAFF_PERMS),
    ("Mentor", "Training mentor access", True, [
        "admin_panel.access", "training.mentor", "controllers.view_notes",
    ]),
    ("Examiner", "Examiner access", True, [
        "admin_panel.access", "training.mentor", "training.examine",
        "controllers.view_notes",
    ]),
]


def seed(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    RoleProfile = apps.get_model("accounts", "RoleProfile")

    perm_objects = {}
    for codename, name, category in DEFAULT_PERMISSIONS:
        perm, _ = Permission.objects.get_or_create(
            codename=codename, defaults={"name": name, "category": category}
        )
        perm_objects[codename] = perm

    for name, description, is_system, perm_codenames in ROLE_PROFILES:
        profile, _ = RoleProfile.objects.get_or_create(
            name=name, defaults={"description": description, "is_system": is_system}
        )
        profile.permissions.set([perm_objects[c] for c in perm_codenames])


def unseed(apps, schema_editor):
    RoleProfile = apps.get_model("accounts", "RoleProfile")
    Permission = apps.get_model("accounts", "Permission")
    RoleProfile.objects.filter(is_system=True).delete()
    Permission.objects.filter(codename__in=[p[0] for p in DEFAULT_PERMISSIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_permission_roleprofile_userpermission_userrole'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
