# Generated by Django 6.0.3 on 2026-04-06 15:35

from django.db import migrations


ROLE_TYPE_TO_PROFILE = {
    "SUPERADMIN": "Superadmin",
    "ADMIN": "Admin",
    "STAFF": "Staff",
    "MENTOR": "Mentor",
    "EXAMINER": "Examiner",
}


def migrate_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    RoleProfile = apps.get_model("accounts", "RoleProfile")
    UserRole = apps.get_model("accounts", "UserRole")

    profiles = {rp.name: rp for rp in RoleProfile.objects.all()}

    for old_role in Role.objects.all():
        profile_name = ROLE_TYPE_TO_PROFILE.get(old_role.role)
        if not profile_name or profile_name not in profiles:
            continue
        UserRole.objects.get_or_create(
            user=old_role.user,
            role_profile=profiles[profile_name],
            defaults={"granted_by": old_role.granted_by},
        )


def unmigrate_roles(apps, schema_editor):
    UserRole = apps.get_model("accounts", "UserRole")
    UserRole.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_permissions_and_roles'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, unmigrate_roles),
    ]
