# Generated by Django 6.0.4 on 2026-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userrole_granted_by_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='discord_feedback_channel_id',
            field=models.CharField(blank=True, help_text='Channel for feedback notifications', max_length=20),
        ),
    ]
