# Generated by Django 6.0.4 on 2026-04-10 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this key', max_length=100)),
                ('prefix', models.CharField(db_index=True, help_text='First 12 chars of the key for identification', max_length=12)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the full key', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='URL path after /api/custom/ — e.g. plugins/a/b/config', max_length=500, unique=True)),
                ('name', models.CharField(help_text='Descriptive name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('application/json', 'JSON'), ('text/plain', 'Plain Text'), ('text/html', 'HTML'), ('application/xml', 'XML'), ('text/csv', 'CSV')], default='application/json', max_length=50)),
                ('response_body', models.TextField(help_text='The response body. For JSON, must be valid JSON.')),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Endpoint',
                'verbose_name_plural': 'Custom Endpoints',
                'ordering': ['path'],
            },
        ),
    ]
