# Generated by Django 6.0.3 on 2026-03-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controllers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_rating', models.PositiveSmallIntegerField(help_text='The rating being trained towards (e.g. 2=S1, 3=S2)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentoring_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Request',
                'verbose_name_plural': 'Training Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Visible to mentors only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_notes', to='training.trainingrequest')),
            ],
            options={
                'verbose_name': 'Training Note',
                'verbose_name_plural': 'Training Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('session_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('CPT', 'Controller Practical Test'), ('OTS', 'Over-The-Shoulder')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('student_performance', models.CharField(blank=True, choices=[('BELOW', 'Below Expectations'), ('MEETS', 'Meets Expectations'), ('EXCEEDS', 'Exceeds Expectations')], max_length=20)),
                ('passed', models.BooleanField(blank=True, help_text='For CPT/OTS sessions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions_as_mentor', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controllers.position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions_as_student', to=settings.AUTH_USER_MODEL)),
                ('training_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.trainingrequest')),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-session_date'],
            },
        ),
    ]
