# Generated by Django 6.0.3 on 2026-03-31 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'OBS → S2'", max_length=100)),
                ('from_rating', models.PositiveSmallIntegerField(help_text='Starting rating (1=OBS, 2=S1, etc.)')),
                ('to_rating', models.PositiveSmallIntegerField(help_text='Target rating')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Training Course',
                'verbose_name_plural': 'Training Courses',
                'ordering': ['display_order', 'from_rating'],
            },
        ),
        migrations.AlterModelOptions(
            name='trainingrequest',
            options={'ordering': ['position', 'created_at'], 'verbose_name': 'Training Request', 'verbose_name_plural': 'Training Requests'},
        ),
        migrations.RemoveField(
            model_name='trainingrequest',
            name='assigned_mentor',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='student_performance',
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position in the waiting list (lower = higher priority)'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='requested_rating',
            field=models.PositiveSmallIntegerField(help_text='The rating being trained towards'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting List'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('WITHDRAWN', 'Withdrawn')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal mentor notes'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('CPT', 'Controller Practical Test'), ('OTS', 'Over-The-Shoulder'), ('SIM', 'Simulator')], max_length=20),
        ),
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Overall session summary (Markdown supported)')),
                ('is_published', models.BooleanField(default=False, help_text='When published, the student can view this report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='training.trainingsession')),
            ],
            options={
                'verbose_name': 'Session Report',
                'verbose_name_plural': 'Session Reports',
            },
        ),
        migrations.CreateModel(
            name='TrainingCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Phraseology', 'Strip Management'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'Training Competency',
                'verbose_name_plural': 'Training Competencies',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='training.trainingcourse'),
        ),
        migrations.CreateModel(
            name='TrainingTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Ground Theory Exam'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(blank=True, choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('CPT', 'Controller Practical Test'), ('OTS', 'Over-The-Shoulder'), ('SIM', 'Simulator')], help_text='If set, auto-completes when a session of this type is marked completed', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_definitions', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'Training Task',
                'verbose_name_plural': 'Training Tasks',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 'N/A'), (1, 'Poor'), (2, 'Insufficient'), (3, 'Acceptable'), (4, 'Sufficient'), (5, 'Exam Standard')], default=0)),
                ('comment', models.TextField(blank=True, help_text='Markdown supported')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='training.sessionreport')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='training.trainingcompetency')),
            ],
            options={
                'verbose_name': 'Competency Rating',
                'verbose_name_plural': 'Competency Ratings',
                'unique_together': {('report', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='StudentTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.trainingsession')),
                ('training_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='training.trainingrequest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='training.trainingtaskdefinition')),
            ],
            options={
                'verbose_name': 'Task Progress',
                'verbose_name_plural': 'Task Progress',
                'unique_together': {('training_request', 'task')},
            },
        ),
    ]
