# Generated by Django 6.0.3 on 2026-04-01 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingcourse_alter_trainingrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='is_adhoc',
            field=models.BooleanField(default=False, help_text='Adhoc session not tied to a training programme'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='training_request',
            field=models.ForeignKey(blank=True, help_text='Null for adhoc/recurrency sessions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.trainingrequest'),
        ),
        migrations.CreateModel(
            name='TrainingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_availability', to=settings.AUTH_USER_MODEL)),
                ('booked_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_slot', to='training.trainingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_availability', to=settings.AUTH_USER_MODEL)),
                ('training_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='training.trainingrequest')),
            ],
            options={
                'verbose_name': 'Training Availability',
                'verbose_name_plural': 'Training Availability',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
