# Generated by Django 6.0.3 on 2026-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_documentcategory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_level',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('AUTHENTICATED', 'Authenticated Users'), ('APPROVED_CONTROLLERS', 'Approved Controllers Only')], default='PUBLIC', help_text='Who can view this document', max_length=25),
        ),
    ]
