# Generated by Django 6.0.4 on 2026-04-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_document_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(help_text='e.g. Dublin Airport', max_length=200)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('elevation_ft', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Briefing notes, procedures, etc.')),
                ('is_visible', models.BooleanField(default=True, help_text='Show on the airports page')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['display_order', 'icao'],
            },
        ),
        migrations.CreateModel(
            name='NOTAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notam_id', models.IntegerField(help_text='CADS NOTAM ID', unique=True)),
                ('notam_number', models.CharField(blank=True, max_length=30)),
                ('icao_location', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(help_text='NEW, REPLACE, or CANCELLED', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('icao_text', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('radius_nm', models.FloatField(blank=True, null=True)),
                ('begin_position', models.DateTimeField(blank=True, null=True)),
                ('end_position', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NOTAM',
                'verbose_name_plural': 'NOTAMs',
                'ordering': ['-begin_position'],
            },
        ),
    ]
