# Generated by Django 6.0.4 on 2026-04-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_airport_and_notam_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='chart_ad_url',
            field=models.URLField(blank=True, help_text='Aerodrome chart URL'),
        ),
        migrations.AddField(
            model_name='airport',
            name='chart_extra_urls',
            field=models.TextField(blank=True, help_text='Additional chart links, one per line in format: Label|URL'),
        ),
        migrations.AddField(
            model_name='airport',
            name='chart_ground_url',
            field=models.URLField(blank=True, help_text='Ground movement chart URL'),
        ),
        migrations.AddField(
            model_name='airport',
            name='chart_iap_url',
            field=models.URLField(blank=True, help_text='Instrument approach chart URL'),
        ),
        migrations.AddField(
            model_name='airport',
            name='chart_sid_url',
            field=models.URLField(blank=True, help_text='SID chart URL'),
        ),
        migrations.AddField(
            model_name='airport',
            name='chart_star_url',
            field=models.URLField(blank=True, help_text='STAR chart URL'),
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(help_text='e.g. 28L, 10R, 16', max_length=3)),
                ('heading', models.PositiveSmallIntegerField(help_text='Magnetic heading in degrees (0-360)')),
                ('length_m', models.PositiveIntegerField(default=0, help_text='Length in metres')),
                ('is_preferential', models.BooleanField(default=False, help_text='This runway is preferred when tailwind is within the threshold')),
                ('max_tailwind_kt', models.PositiveSmallIntegerField(default=5, help_text='Maximum tailwind component (knots) before switching off this runway')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='public.airport')),
            ],
            options={
                'verbose_name': 'Runway',
                'verbose_name_plural': 'Runways',
                'ordering': ['designator'],
                'unique_together': {('airport', 'designator')},
            },
        ),
    ]
