# Generated by Django 6.0.4 on 2026-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_airport_charts_and_runways'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runway',
            name='is_preferential',
        ),
        migrations.AddField(
            model_name='runway',
            name='preferential_arrival',
            field=models.BooleanField(default=False, help_text='Preferred for arrivals when tailwind is within threshold'),
        ),
        migrations.AddField(
            model_name='runway',
            name='preferential_departure',
            field=models.BooleanField(default=False, help_text='Preferred for departures when tailwind is within threshold'),
        ),
    ]
