# Generated by Django 6.0.4 on 2026-04-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_runway_split_preferential'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='staff_notice',
            field=models.TextField(blank=True, help_text='Staff notice/warning displayed at the top of the briefing page'),
        ),
    ]
