# Generated by Django 6.0.4 on 2026-04-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_airport_staff_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='show_metar_on_homepage',
            field=models.BooleanField(default=False, help_text='Display METAR on the homepage'),
        ),
    ]
