# Generated by Django 6.0.3 on 2026-03-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(blank=True, max_length=200)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('submitter_cid', models.PositiveIntegerField(blank=True, null=True)),
                ('controller_callsign', models.CharField(blank=True, help_text='Callsign of the controller this feedback is about', max_length=20)),
                ('feedback_type', models.CharField(choices=[('COMPLIMENT', 'Compliment'), ('CONCERN', 'Concern'), ('SUGGESTION', 'Suggestion'), ('BUG_REPORT', 'Bug Report')], default='COMPLIMENT', max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('ACTIONED', 'Actioned'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
