# Generated by Django 6.0.3 on 2026-03-30 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='controller',
            field=models.ForeignKey(blank=True, help_text='Controller this feedback is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_received', to='controllers.controller'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submitter_cid',
            field=models.PositiveIntegerField(blank=True, help_text='VATSIM CID of the submitter', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submitter_name',
            field=models.CharField(max_length=200),
        ),
    ]
