# Generated by Django 6.0.3 on 2026-04-06 19:30

from django.db import migrations


def backfill(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    TicketReply = apps.get_model("tickets", "TicketReply")
    for ticket in Ticket.objects.all():
        last_reply = TicketReply.objects.filter(
            ticket=ticket, is_internal_note=False
        ).order_by("-created_at").first()
        if last_reply:
            ticket.last_replied_by = last_reply.author
            ticket.last_replied_at = last_reply.created_at
            ticket.save(update_fields=["last_replied_by", "last_replied_at"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_ticket_last_replied_at_ticket_last_replied_by"),
    ]
    operations = [
        migrations.RunPython(backfill, noop),
    ]
