# Generated by Django 6.0.3 on 2026-03-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('cid', models.PositiveIntegerField(help_text='VATSIM Certificate ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField(default=1, help_text='VATSIM rating integer (1=OBS ... 12=ADM)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_home_controller', models.BooleanField(default=True, help_text='Belongs to VATéir (vs visitor)')),
                ('notes', models.TextField(blank=True)),
                ('backfill_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('backfill_started_at', models.DateTimeField(blank=True, null=True)),
                ('backfill_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Controller',
                'verbose_name_plural': 'Controllers',
                'ordering': ['cid'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text="Friendly name, e.g. 'Dublin Tower'", max_length=100)),
                ('position_type', models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('GROUND', 'Ground'), ('TOWER', 'Tower'), ('APPROACH', 'Approach'), ('ACC', 'ACC')], max_length=10)),
                ('airport_icao', models.CharField(blank=True, help_text='e.g. EIDW, EINN', max_length=4)),
                ('frequency', models.CharField(blank=True, max_length=10)),
                ('is_home', models.BooleanField(db_index=True, default=False, help_text='Position belongs to the home FIR (EI*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['callsign'],
            },
        ),
        migrations.CreateModel(
            name='ControllerStats',
            fields=[
                ('controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='controllers.controller')),
                ('atc', models.FloatField(default=0.0, help_text='Total ATC hours')),
                ('pilot', models.FloatField(default=0.0, help_text='Total pilot hours')),
                ('s1', models.FloatField(default=0.0)),
                ('s2', models.FloatField(default=0.0)),
                ('s3', models.FloatField(default=0.0)),
                ('c1', models.FloatField(default=0.0)),
                ('c2', models.FloatField(default=0.0)),
                ('c3', models.FloatField(default=0.0)),
                ('i1', models.FloatField(default=0.0)),
                ('i2', models.FloatField(default=0.0)),
                ('i3', models.FloatField(default=0.0)),
                ('sup', models.FloatField(default=0.0)),
                ('adm', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Controller Stats',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('cid', models.PositiveIntegerField(db_index=True)),
                ('callsign', models.CharField(db_index=True, max_length=20)),
                ('frequency', models.CharField(blank=True, max_length=20)),
                ('facility', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(default=1)),
                ('server', models.CharField(blank=True, max_length=50)),
                ('logon_time', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='controllers.controller')),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'ordering': ['-logon_time'],
            },
        ),
        migrations.CreateModel(
            name='ATCSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.BigIntegerField(db_index=True, unique=True)),
                ('cid', models.PositiveIntegerField(db_index=True)),
                ('callsign', models.CharField(db_index=True, max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=1)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField()),
                ('duration_minutes', models.FloatField(default=0.0)),
                ('server', models.CharField(blank=True, max_length=50)),
                ('aircraft_tracked', models.PositiveIntegerField(default=0)),
                ('aircraft_seen', models.PositiveIntegerField(default=0)),
                ('flights_amended', models.PositiveIntegerField(default=0)),
                ('handoffs_initiated', models.PositiveIntegerField(default=0)),
                ('handoffs_received', models.PositiveIntegerField(default=0)),
                ('handoffs_refused', models.PositiveIntegerField(default=0)),
                ('squawks_assigned', models.PositiveIntegerField(default=0)),
                ('cruise_alts_modified', models.PositiveIntegerField(default=0)),
                ('temp_alts_modified', models.PositiveIntegerField(default=0)),
                ('scratchpad_mods', models.PositiveIntegerField(default=0)),
                ('is_backfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='controllers.controller')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='controllers.position')),
            ],
            options={
                'verbose_name': 'ATC Session',
                'verbose_name_plural': 'ATC Sessions',
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['cid', 'start'], name='controllers_cid_aa1360_idx'), models.Index(fields=['callsign', 'start'], name='controllers_callsig_247545_idx')],
            },
        ),
    ]
