# Generated by Django 6.0.3 on 2026-04-01 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to='controllers.controller')),
            ],
            options={
                'verbose_name': 'Controller Note',
                'verbose_name_plural': 'Controller Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
