# Generated by Django 6.0.3 on 2026-04-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0002_controllernote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='home_division',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='controller',
            name='home_subdivision',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='controller',
            name='visitor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='visitor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controller',
            name='visitor_status',
            field=models.CharField(choices=[('NONE', 'None (Home Controller)'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='NONE', help_text='NONE for home controllers, APPROVED/PENDING/etc for visitors', max_length=20),
        ),
    ]
