# Generated by Django 6.0.3 on 2026-04-06 15:52

from django.db import migrations


def migrate_visitor_status(apps, schema_editor):
    Controller = apps.get_model("controllers", "Controller")
    Controller.objects.filter(is_home_controller=True).update(visitor_status="NONE")
    Controller.objects.filter(is_home_controller=False).update(visitor_status="APPROVED")


def unmigrate(apps, schema_editor):
    Controller = apps.get_model("controllers", "Controller")
    Controller.objects.filter(visitor_status="NONE").update(is_home_controller=True)
    Controller.objects.exclude(visitor_status="NONE").update(is_home_controller=False)


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0003_remove_controller_is_home_controller_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_visitor_status, unmigrate),
    ]
