# Generated by Django 6.0.3 on 2026-04-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0004_migrate_visitor_status'),
    ]

    operations = [
        migrations.RemoveField(model_name="controller", name="is_home_controller"),
    ]
