# Generated by Django 6.0.4 on 2026-04-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0005_remove_is_home_controller'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vateud_id', models.PositiveIntegerField(help_text='ID from VATEUD API', unique=True)),
                ('cid', models.PositiveIntegerField(db_index=True, help_text='Applicant VATSIM CID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(help_text='From VATEUD API')),
                ('updated_at', models.DateTimeField(help_text='From VATEUD API')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_requests', to='controllers.controller')),
            ],
            options={
                'verbose_name': 'Visitor Request',
                'verbose_name_plural': 'Visitor Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vateud_id', models.PositiveIntegerField(help_text='ID from VATEUD API (unique per type, not globally)')),
                ('cid', models.PositiveIntegerField(db_index=True, help_text='VATSIM CID')),
                ('type', models.CharField(choices=[('SOLO', 'Solo'), ('TIER_1', 'Tier 1'), ('TIER_2', 'Tier 2')], max_length=10)),
                ('position', models.CharField(help_text='Callsign, e.g. EIDW_TWR', max_length=20)),
                ('instructor_cid', models.PositiveIntegerField(help_text='CID of granting instructor')),
                ('facility', models.PositiveIntegerField(default=0, help_text='VATEUD facility ID')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Solo endorsements only', null=True)),
                ('max_days', models.PositiveIntegerField(blank=True, help_text='Solo endorsements only', null=True)),
                ('created_at', models.DateTimeField(help_text='From VATEUD API')),
                ('updated_at', models.DateTimeField(help_text='From VATEUD API')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsements', to='controllers.controller')),
            ],
            options={
                'verbose_name': 'Endorsement',
                'verbose_name_plural': 'Endorsements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='controllers_type_a936af_idx')],
                'constraints': [models.UniqueConstraint(fields=('vateud_id', 'type'), name='unique_endorsement_per_type')],
            },
        ),
    ]
