# Generated by Django 6.0.4 on 2026-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0006_endorsement_visitorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='min_rating',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum VATSIM rating required (1=OBS, 2=S1, etc.)'),
        ),
    ]
