# Generated by Django 6.0.4 on 2026-04-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0007_position_min_rating'),
        ('public', '0006_runway_split_preferential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='airport_icao',
        ),
        migrations.AddField(
            model_name='position',
            name='airport',
            field=models.ForeignKey(blank=True, help_text='Airport this position belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='public.airport'),
        ),
    ]
