# Generated by Django 6.0.4 on 2026-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0008_airport_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='on_roster',
            field=models.BooleanField(db_index=True, default=False, help_text='Controller is on the VATEUD facility roster'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='visitor_status',
            field=models.CharField(choices=[('NONE', 'Home Controller'), ('PENDING', 'Pending Visitor'), ('APPROVED', 'Approved Visitor'), ('REJECTED', 'Rejected Visitor'), ('REVOKED', 'Revoked Visitor')], default='NONE', help_text='NONE for home controllers, APPROVED/PENDING/etc for visitors', max_length=20),
        ),
    ]
