# Generated by Django 6.0.3 on 2026-04-01 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('channel_id', models.CharField(max_length=20)),
                ('channel_name', models.CharField(blank=True, max_length=100)),
                ('embed_color', models.CharField(default='#059669', max_length=7)),
                ('banner_image_url', models.URLField(blank=True)),
                ('announcement_type', models.CharField(choices=[('GENERAL', 'General'), ('EVENT', 'Event'), ('EXAM', 'Exam'), ('TRAINING', 'Training')], default='GENERAL', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('discord_message_id', models.CharField(blank=True, max_length=20)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discord Announcement',
                'verbose_name_plural': 'Discord Announcements',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscordBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(max_length=20)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('unbanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('also_site_banned', models.BooleanField(default=False, help_text="Whether the user's website account was also deactivated")),
                ('guild_id', models.CharField(max_length=20)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL)),
                ('unbanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unbans_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discord Ban',
                'verbose_name_plural': 'Discord Bans',
                'ordering': ['-banned_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscordBotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Log',
                'verbose_name_plural': 'Bot Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
